from tkinter import *
window=Tk()
window.title("demo window")
window.geomentry("300x300")
greeting=Label(text="hello welcome to the demo window", bg="blue",fg="white")
button=Button(text="click",bg="black",fg="white")
entry=Entry(fg="red",bg="orange")
greeting.pack()
button.pack()
entry.pack()
frame=Frame(master=window,relief=RAISED,borderwidth=4)
frame.pack()
label1=Label(master=frame,text="smaple frame")
label1.pack()
textbox=Text(bg="green",fg="white")
window.mainloop()
